algoritmo "Questão 01"
// Função : Calcula a idade de uma pessoa
// Autor :  Edson Júnior Frota da Silva
// Data : 17/10/2015
// Seção de Declarações
var
   nas, ano, media, futuro :inteiro
inicio
escreva ("Em que ano voce nasceu? ")
leia (nas)
escreva ("Em que ano nos estamos? ")
leia (ano)
media <-  ano - nas
futuro <- 2050 - nas
escreva (media , " anos é sua idade")
escreva (", e em 2050 séra" , futuro, " anos" )

fimalgoritmo
