algoritmo "EXEPLO 1"
// Função :
// Autor :
// Data : 07/11/2015
// Seção de Declarações 
var
codigo:inteiro
inicio
escreva("Digite o código de origem:  ")
leia(codigo)
escreval("") //Apenas para pular Linaha
escolha(codigo)
caso 1
escreval ("SUL")
caso 2
escreval("NORTE")
caso 3, 4
escreval("NORDESTE")
caso 5, 6, 7
escreval("SUDESTE")
caso 8, 9, 10
escreval("CENTRO-OESTE")
outrocaso
escreval("PRODUTO IMPORTADO")
fimescolha
fimalgoritmo
