algoritmo "Exemplo 2"
// Função :
// Autor :
// Data : 07/11/2015
// Seção de Declarações
var
cargo:inteiro
inicio
escreva("DIGITE O CARGO:  ")
leia(cargo)
escreval(" ")
escolha(cargo)
caso 1
   escreval("cargo ESCRITURÁRIO, 50%")
caso 2
   escreval("cargo SECRETÁRIO, 35%")
caso 3
   escreval("cargo CAIXA, 20%")
CASO 4
   escreval("cargo GERENTE, 10%")
caso 5
   escreval("cargo DIRETOR, não tem aumento")
outrocaso
   escreval("Código Inválido")
fimescolha
fimalgoritmo
