algoritmo "Questão 13"
// Função :Informa a ordem crescente de dois números
// Autor :Edson Júnior Frota da Silva
// Data : 24/10/2015
// Seção de Declarações
var
a, b :inteiro
inicio
escreva ("Digite o primeiro número:")
leia (a)
escreva ("Digite o segundo número:")
leia (b)
se ((a < b) e (b > a)) entao
   escreval (a ,",", b)
senao ((b < a) e (a < b) entao
   escreval (b , ",", a)
fimse
fimalgoritmo
