algoritmo "Questã 05"
// Função :Informa se um numero está na faixa de 100 a 1000
// Autor :Edson Júnior Frota da Silva
// Data : 24/10/2015
// Seção de Declarações 
var
a :inteiro
inicio
escreva("Informe um número:")
leia (a)
se ((a >= 100) e (a <= 1000)) entao
escreval ("O número", a , " está na faixa entre 100 a 1000")
senao (a < 100) e (a > 1000) entao
escreval ("O número", a,  " não está na faixa de 100 a 1000")
fimse
fimalgoritmo
